name: Wiki.js Compatibility Testing

on:
  workflow_dispatch:

jobs:
  # --- Job chạy trên Ubuntu (Chrome + Firefox) ---
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [14, 18, 20]
        database: [postgresql, mysql, mongodb]
        browser: [chrome, firefox]

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: wikijs
          POSTGRES_PASSWORD: wikijsrocks
          POSTGRES_DB: wiki
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U wikijs"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: wikijsrocks
          MYSQL_DATABASE: wiki
          MYSQL_USER: wikijs
          MYSQL_PASSWORD: wikijsrocks
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u wikijs --password=wikijsrocks"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")' || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: mainrepo

      - name: Checkout Wiki.js source
        run: |
          wget https://github.com/Requarks/wiki/releases/latest/download/wiki-js.tar.gz
          mkdir wikijs
          tar xzf wiki-js.tar.gz -C ./wikijs
          cd wikijs
          mv config.sample.yml config.yml

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: |
          cd wikijs
          npm install --no-audit --no-fund --legacy-peer-deps

      - name: Set Database ENV
        run: |
          if [ "${{ matrix.database }}" = "postgresql" ]; then
            echo "DB_TYPE=postgres" >> $GITHUB_ENV
            echo "DB_HOST=localhost" >> $GITHUB_ENV
            echo "DB_PORT=5432" >> $GITHUB_ENV
            echo "DB_USER=wikijs" >> $GITHUB_ENV
            echo "DB_PASS=wikijsrocks" >> $GITHUB_ENV
            echo "DB_NAME=wiki" >> $GITHUB_ENV
          elif [ "${{ matrix.database }}" = "mysql" ]; then
            echo "DB_TYPE=mysql" >> $GITHUB_ENV
            echo "DB_HOST=localhost" >> $GITHUB_ENV
            echo "DB_PORT=3306" >> $GITHUB_ENV
            echo "DB_USER=wikijs" >> $GITHUB_ENV
            echo "DB_PASS=wikijsrocks" >> $GITHUB_ENV
            echo "DB_NAME=wiki" >> $GITHUB_ENV
          elif [ "${{ matrix.database }}" = "mongodb" ]; then
            echo "DB_TYPE=mongodb" >> $GITHUB_ENV
            echo "DB_HOST=localhost" >> $GITHUB_ENV
            echo "DB_PORT=27017" >> $GITHUB_ENV
            echo "DB_NAME=wiki" >> $GITHUB_ENV
          fi

      - name: Build Wiki.js
        run: |
          cd wikijs
          echo "Running Wiki.js build on Node ${{ matrix.node }} with DB ${{ matrix.database }} and Browser ${{ matrix.browser }}"
          npm rebuild sqlite3
          
      - name: Start Wiki.js server
        run: |
          cd wikijs
          nohup node server > server.log 2>&1 &
          sleep 20
          cat server.log

      - name: Test server response
        run: |
          cd wikijs
          curl -I http://localhost:3000 || (cat server.log && exit 1)

  # --- Job chạy Safari riêng trên macOS ---
  test-safari:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        node: [14, 18, 20]
        database: [postgresql, mysql, mongodb]
        browser: [safari]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: mainrepo

      - name: Checkout Wiki.js source
        run: |
          wget https://github.com/Requarks/wiki/releases/latest/download/wiki-js.tar.gz
          mkdir wikijs
          tar xzf wiki-js.tar.gz -C ./wikijs
          cd wikijs
          mv config.sample.yml config.yml

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      # --- Cài DB theo matrix ---
      - name: Setup Database
        run: |
          if [ "${{ matrix.database }}" = "postgresql" ]; then
            brew install postgresql@15
            brew services start postgresql@15
            sleep 10
            createdb wiki
            psql -d postgres -c "CREATE USER wikijs WITH PASSWORD 'wikijsrocks';"
            psql -d postgres -c "GRANT ALL PRIVILEGES ON DATABASE wiki TO wikijs;"
            echo "DB_TYPE=postgres" >> $GITHUB_ENV
            echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
            echo "DB_PORT=5432" >> $GITHUB_ENV
            echo "DB_USER=wikijs" >> $GITHUB_ENV
            echo "DB_PASS=wikijsrocks" >> $GITHUB_ENV
            echo "DB_NAME=wiki" >> $GITHUB_ENV
          elif [ "${{ matrix.database }}" = "mysql" ]; then
            brew install mysql
            brew services start mysql
            sleep 10
            mysql -uroot -e "CREATE DATABASE wiki;"
            mysql -uroot -e "CREATE USER 'wikijs'@'localhost' IDENTIFIED BY 'wikijsrocks';"
            mysql -uroot -e "GRANT ALL PRIVILEGES ON wiki.* TO 'wikijs'@'localhost';"
            echo "DB_TYPE=mysql" >> $GITHUB_ENV
            echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
            echo "DB_PORT=3306" >> $GITHUB_ENV
            echo "DB_USER=wikijs" >> $GITHUB_ENV
            echo "DB_PASS=wikijsrocks" >> $GITHUB_ENV
            echo "DB_NAME=wiki" >> $GITHUB_ENV
          elif [ "${{ matrix.database }}" = "mongodb" ]; then
            brew tap mongodb/brew
            brew install mongodb-community@6.0
            brew services start mongodb-community@6.0
            sleep 10
            echo "DB_TYPE=mongodb" >> $GITHUB_ENV
            echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
            echo "DB_PORT=27017" >> $GITHUB_ENV
            echo "DB_NAME=wiki" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        run: |
          cd wikijs
          npm install --no-audit --no-fund --legacy-peer-deps

      - name: Build Wiki.js
        run: |
          cd wikijs
          echo "Running Wiki.js build on Node ${{ matrix.node }} with DB ${{ matrix.database }} and Browser Safari"
          npm rebuild sqlite3
          
      - name: Start Wiki.js server
        run: |
          cd wikijs
          nohup node server > server.log 2>&1 &
          sleep 20
          cat server.log

      - name: Test server response
        run: |
          cd wikijs
          curl -I http://localhost:3000 || (cat server.log && exit 1)

