name: Wiki.js Compatibility Testing

on:
  workflow_dispatch:

jobs:
  test-safari:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        node: [14, 18, 20]
        database: [postgresql, mysql, mongodb]
        browser: [safari]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: mainrepo

      - name: Checkout Wiki.js source
        run: |
          wget https://github.com/Requarks/wiki/releases/latest/download/wiki-js.tar.gz
          mkdir wikijs
          tar xzf wiki-js.tar.gz -C ./wikijs
          cd wikijs
          mv config.sample.yml config.yml

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      # --- Cài và khởi động Database ---
      - name: Setup Database
        run: |
          if [ "${{ matrix.database }}" = "mysql" ]; then
            brew install mysql
            echo 'export PATH="/usr/local/opt/mysql/bin:$PATH"' >> $HOME/.bash_profile
            export PATH="/usr/local/opt/mysql/bin:$PATH"
            brew services start mysql
            sleep 15

            # root mặc định không có password nên kết nối không cần -p
            mysql -uroot -e "DROP DATABASE IF EXISTS wiki;"
            mysql -uroot -e "CREATE DATABASE wiki;"
            mysql -uroot -e "DROP USER IF EXISTS 'wikijs'@'localhost';"
            mysql -uroot -e "CREATE USER 'wikijs'@'localhost' IDENTIFIED WITH caching_sha2_password BY 'wikijsrocks';"
            mysql -uroot -e "GRANT ALL PRIVILEGES ON wiki.* TO 'wikijs'@'localhost';"
            mysql -uroot -e "FLUSH PRIVILEGES;"

            echo "DB_TYPE=mysql" >> $GITHUB_ENV
            echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
            echo "DB_PORT=3306" >> $GITHUB_ENV
            echo "DB_USER=wikijs" >> $GITHUB_ENV
            echo "DB_PASS=wikijsrocks" >> $GITHUB_ENV
            echo "DB_NAME=wiki" >> $GITHUB_ENV
          fi




