name: Compatibility Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [16, 18, 20]
        browser: [chrome, firefox]
        database: [postgresql, mysql, mongodb]

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: wikijs
          POSTGRES_PASSWORD: wikijs
          POSTGRES_DB: wikijs
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U wikijs"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: wikijs
          MYSQL_DATABASE: wikijs
          MYSQL_USER: wikijs
          MYSQL_PASSWORD: wikijs
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u wikijs --password=wikijs"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongo --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Set Database ENV
        run: |
          if [ "${{ matrix.database }}" = "postgresql" ]; then
            echo "DB_TYPE=postgres" >> $GITHUB_ENV
            echo "DB_HOST=localhost" >> $GITHUB_ENV
            echo "DB_PORT=5432" >> $GITHUB_ENV
            echo "DB_USER=wikijs" >> $GITHUB_ENV
            echo "DB_PASS=wikijs" >> $GITHUB_ENV
            echo "DB_NAME=wikijs" >> $GITHUB_ENV
          elif [ "${{ matrix.database }}" = "mysql" ]; then
            echo "DB_TYPE=mysql" >> $GITHUB_ENV
            echo "DB_HOST=localhost" >> $GITHUB_ENV
            echo "DB_PORT=3306" >> $GITHUB_ENV
            echo "DB_USER=wikijs" >> $GITHUB_ENV
            echo "DB_PASS=wikijs" >> $GITHUB_ENV
            echo "DB_NAME=wikijs" >> $GITHUB_ENV
          elif [ "${{ matrix.database }}" = "mongodb" ]; then
            echo "DB_TYPE=mongodb" >> $GITHUB_ENV
            echo "DB_HOST=localhost" >> $GITHUB_ENV
            echo "DB_PORT=27017" >> $GITHUB_ENV
            echo "DB_NAME=wikijs" >> $GITHUB_ENV
          fi

      - name: Run Tests
        run: |
          echo "Running tests on Node ${{ matrix.node }} with DB ${{ matrix.database }} and Browser ${{ matrix.browser }}"
          npm run test
