name: Wiki.js Compatibility Testing

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - node: 16
            browser: chrome
            database: postgresql
          - node: 18
            browser: firefox
            database: mysql
          - node: 20
            browser: chrome
            database: mongodb

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: wikijs
          POSTGRES_PASSWORD: wikijs
          POSTGRES_DB: wikijs
        ports:
          - 5432/tcp
        options: >-
          --health-cmd="pg_isready -U wikijs"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: wikijs
          MYSQL_DATABASE: wikijs
          MYSQL_USER: wikijs
          MYSQL_PASSWORD: wikijs
        ports:
          - 3306/tcp
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u wikijs --password=wikijs"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      mongo:
        image: mongo:6
        ports:
          - 27017/tcp
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")' || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Wiki.js repo
        uses: actions/checkout@v4

      - name: Checkout Wiki.js source
        uses: actions/checkout@v4
        with:
          repository: requarks/wiki
          ref: master
          path: wikijs

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: |
          cd wikijs
          npm install --no-audit --no-fund

      - name: Set Database ENV
        run: |
          if [ "${{ matrix.database }}" = "postgresql" ]; then
            echo "DB_TYPE=postgres" >> $GITHUB_ENV
            echo "DB_HOST=localhost" >> $GITHUB_ENV
            echo "DB_PORT=${{ job.services.postgres.ports[5432] }}" >> $GITHUB_ENV
            echo "DB_USER=wikijs" >> $GITHUB_ENV
            echo "DB_PASS=wikijs" >> $GITHUB_ENV
            echo "DB_NAME=wikijs" >> $GITHUB_ENV
          elif [ "${{ matrix.database }}" = "mysql" ]; then
            echo "DB_TYPE=mysql" >> $GITHUB_ENV
            echo "DB_HOST=localhost" >> $GITHUB_ENV
            echo "DB_PORT=${{ job.services.mysql.ports[3306] }}" >> $GITHUB_ENV
            echo "DB_USER=wikijs" >> $GITHUB_ENV
            echo "DB_PASS=wikijs" >> $GITHUB_ENV
            echo "DB_NAME=wikijs" >> $GITHUB_ENV
          elif [ "${{ matrix.database }}" = "mongodb" ]; then
            echo "DB_TYPE=mongodb" >> $GITHUB_ENV
            echo "DB_HOST=localhost" >> $GITHUB_ENV
            echo "DB_PORT=${{ job.services.mongo.ports[27017] }}" >> $GITHUB_ENV
            echo "DB_NAME=wikijs" >> $GITHUB_ENV
          fi

      - name: Build Wiki.js
        run: |
          cd wikijs
          echo "Running Wiki.js build on Node ${{ matrix.node }} with DB ${{ matrix.database }} and Browser ${{ matrix.browser }}"
          npm run build
          
      - name: Run Wiki.js Tests
        run: |
          cd wikijs
          echo "Running Wiki.js tests on Node ${{ matrix.node }} with DB ${{ matrix.database }} and Browser ${{ matrix.browser }}"
          npm run test
