name: Wiki.js Compatibility Testing

on:
  workflow_dispatch:

jobs:
  test-safari:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        node: [14, 18, 20]
        database: [postgresql, mysql, mongodb]
        browser: [safari]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: mainrepo

      - name: Checkout Wiki.js source
        run: |
          wget https://github.com/Requarks/wiki/releases/latest/download/wiki-js.tar.gz
          mkdir wikijs
          tar xzf wiki-js.tar.gz -C ./wikijs
          cd wikijs
          mv config.sample.yml config.yml

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      # --- Cài và khởi động Database ---
      - name: Setup Database
        run: |
          if [ "${{ matrix.database }}" = "postgresql" ]; then
            brew install postgresql@15
            # add vào PATH
            echo 'export PATH="/usr/local/opt/postgresql@15/bin:$PATH"' >> $HOME/.bash_profile
            export PATH="/usr/local/opt/postgresql@15/bin:$PATH"
            brew services start postgresql@15
            sleep 15

            # tạo user + db
            psql -d postgres -c "DROP DATABASE IF EXISTS wiki;" || true
            psql -d postgres -c "DROP USER IF EXISTS wikijs;" || true
            psql -d postgres -c "CREATE USER wikijs WITH PASSWORD 'wikijsrocks';"
            psql -d postgres -c "CREATE DATABASE wiki OWNER wikijs;"

            echo "DB_TYPE=postgres" >> $GITHUB_ENV
            echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
            echo "DB_PORT=5432" >> $GITHUB_ENV
            echo "DB_USER=wikijs" >> $GITHUB_ENV
            echo "DB_PASS=wikijsrocks" >> $GITHUB_ENV
            echo "DB_NAME=wiki" >> $GITHUB_ENV

          elif [ "${{ matrix.database }}" = "mysql" ]; then
            brew install mysql
            # add vào PATH
            echo 'export PATH="/usr/local/opt/mysql/bin:$PATH"' >> $HOME/.bash_profile
            export PATH="/usr/local/opt/mysql/bin:$PATH"
            brew services start mysql
            sleep 15

            # reset root password & tạo user wikijs
            mysql -uroot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'rootpass';" || true
            mysql -uroot -prootpass -e "DROP DATABASE IF EXISTS wiki;"
            mysql -uroot -prootpass -e "CREATE DATABASE wiki;"
            mysql -uroot -prootpass -e "DROP USER IF EXISTS 'wikijs'@'localhost';"
            mysql -uroot -prootpass -e "CREATE USER 'wikijs'@'localhost' IDENTIFIED BY 'wikijsrocks';"
            mysql -uroot -prootpass -e "GRANT ALL PRIVILEGES ON wiki.* TO 'wikijs'@'localhost';"
            mysql -uroot -prootpass -e "FLUSH PRIVILEGES;"

            echo "DB_TYPE=mysql" >> $GITHUB_ENV
            echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
            echo "DB_PORT=3306" >> $GITHUB_ENV
            echo "DB_USER=wikijs" >> $GITHUB_ENV
            echo "DB_PASS=wikijsrocks" >> $GITHUB_ENV
            echo "DB_NAME=wiki" >> $GITHUB_ENV

          elif [ "${{ matrix.database }}" = "mongodb" ]; then
            brew tap mongodb/brew
            brew install mongodb-community@6.0
            brew services start mongodb-community@6.0
            sleep 15

            echo "DB_TYPE=mongodb" >> $GITHUB_ENV
            echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
            echo "DB_PORT=27017" >> $GITHUB_ENV
            echo "DB_NAME=wiki" >> $GITHUB_ENV
          fi



