name: Ubuntu + browser + NodeJS + DB

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - node: 14
            browser: chrome
            database: postgresql
          - node: 18
            browser: firefox
            database: mysql
          - node: 20
            browser: chrome
            database: mongodb

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: wikijs
          POSTGRES_PASSWORD: wikijsrocks
          POSTGRES_DB: wiki
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U wikijs"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: wikijsrocks
          MYSQL_DATABASE: wiki
          MYSQL_USER: wikijs
          MYSQL_PASSWORD: wikijsrocks
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u wikijs --password=wikijs"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")' || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: mainrepo

      - name: Checkout Wiki.js source
        run: |
          wget https://github.com/Requarks/wiki/releases/latest/download/wiki-js.tar.gz
          mkdir wikijs
          tar xzf wiki-js.tar.gz -C ./wikijs
          cd wikijs
          mv config.sample.yml config.yml

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: |
          cd wikijs
          npm install --no-audit --no-fund --legacy-peer-deps

      - name: Set Database ENV
        run: |
          if [ "${{ matrix.database }}" = "postgresql" ]; then
            echo "DB_TYPE=postgres" >> $GITHUB_ENV
            echo "DB_HOST=localhost" >> $GITHUB_ENV
            echo "DB_PORT=5432" >> $GITHUB_ENV
            echo "DB_USER=wikijs" >> $GITHUB_ENV
            echo "DB_PASS=wikijs" >> $GITHUB_ENV
            echo "DB_NAME=wikijs" >> $GITHUB_ENV
          elif [ "${{ matrix.database }}" = "mysql" ]; then
            echo "DB_TYPE=mysql" >> $GITHUB_ENV
            echo "DB_HOST=localhost" >> $GITHUB_ENV
            echo "DB_PORT=3306" >> $GITHUB_ENV
            echo "DB_USER=wikijs" >> $GITHUB_ENV
            echo "DB_PASS=wikijs" >> $GITHUB_ENV
            echo "DB_NAME=wikijs" >> $GITHUB_ENV
          elif [ "${{ matrix.database }}" = "mongodb" ]; then
            echo "DB_TYPE=mongodb" >> $GITHUB_ENV
            echo "DB_HOST=localhost" >> $GITHUB_ENV
            echo "DB_PORT=27017" >> $GITHUB_ENV
            echo "DB_NAME=wikijs" >> $GITHUB_ENV
          fi

      - name: Build Wiki.js
        run: |
          cd wikijs
          echo "Running Wiki.js build on Node ${{ matrix.node }} with DB ${{ matrix.database }} and Browser ${{ matrix.browser }}"
          npm rebuild sqlite3
          
      - name: Start Wiki.js server
        run: |
          cd wikijs
          nohup node server > server.log 2>&1 &
          sleep 20
          cat server.log

      - name: Test server response
        run: |
          cd wikijs
          curl -I http://localhost:3000 || (cat server.log && exit 1)
          
      - name: Install Playwright
        run: |
          npm install -D @playwright/test
          npx playwright install --with-deps

      - name: Run Playwright Tests
        working-directory: mainrepo
        run: |
          ls -l
          npx playwright test --config=playwright.config.ts --project=${{ matrix.browser }}



