name: Compatibility testing
run-name: ubuntu + browser + NodeJS + DB 

on:
  workflow_dispatch:

jobs:
  compatibility-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [14, 18, 20]
        browser: [chrome, firefox]
        database: [postgresql, mysql, mongodb]

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: wikijs
          POSTGRES_PASSWORD: wikijsrocks
          POSTGRES_DB: wiki
        ports:
          - 5432:5432

      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: wikijsrocks
          MYSQL_DATABASE: wiki
          MYSQL_USER: wikijs
          MYSQL_PASSWORD: wikijsrocks
        ports:
          - 3306:3306

      mongo:
        image: mongo:6
        ports:
          - 27017:27017

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: mainrepo

      - name: Checkout Wiki.js source
        run: |
          wget https://github.com/Requarks/wiki/releases/latest/download/wiki-js.tar.gz
          mkdir wikijs
          tar xzf wiki-js.tar.gz -C ./wikijs
          cd wikijs
          mv config.sample.yml config.yml

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: |
          cd wikijs
          npm install --no-audit --no-fund --legacy-peer-deps

      - name: Set Database ENV
        run: |
          if [ "${{ matrix.database }}" = "postgresql" ]; then
            echo "DB_TYPE=postgres" >> $GITHUB_ENV
            echo "DB_HOST=localhost" >> $GITHUB_ENV
            echo "DB_PORT=5432" >> $GITHUB_ENV
            echo "DB_USER=wikijs" >> $GITHUB_ENV
            echo "DB_PASS=wikijsrocks" >> $GITHUB_ENV
            echo "DB_NAME=wiki" >> $GITHUB_ENV
          elif [ "${{ matrix.database }}" = "mysql" ]; then
            echo "DB_TYPE=mysql" >> $GITHUB_ENV
            echo "DB_HOST=localhost" >> $GITHUB_ENV
            echo "DB_PORT=3306" >> $GITHUB_ENV
            echo "DB_USER=wikijs" >> $GITHUB_ENV
            echo "DB_PASS=wikijsrocks" >> $GITHUB_ENV
            echo "DB_NAME=wiki" >> $GITHUB_ENV
          elif [ "${{ matrix.database }}" = "mongodb" ]; then
            echo "DB_TYPE=mongodb" >> $GITHUB_ENV
            echo "DB_HOST=localhost" >> $GITHUB_ENV
            echo "DB_PORT=27017" >> $GITHUB_ENV
            echo "DB_NAME=wiki" >> $GITHUB_ENV
          fi

      - name: Build Wiki.js
        run: |
          cd wikijs
          echo "Running build on Node ${{ matrix.node }} with DB ${{ matrix.database }} and Browser ${{ matrix.browser }}"
          npm rebuild sqlite3
          
      - name: Start Wiki.js server
        run: |
          cd wikijs
          nohup node server > server.log 2>&1 &
          sleep 20
          cat server.log

      - name: Test server response
        run: |
          cd wikijs
          curl -I http://localhost:3000 || (cat server.log && exit 1)
          
      - name: Install Playwright
        run: |
          npm install -D @playwright/test
          npx playwright install --with-deps

      - name: Run Playwright Tests
        working-directory: mainrepo
        run: |
          npx playwright test --config=playwright.config.ts --project=${{ matrix.browser }}
